version: '3.8'

services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - patient-monitoring-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - patient-monitoring-network

  mongo:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - patient-monitoring-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis-data-dev:/data
    networks:
      - patient-monitoring-network

networks:
  patient-monitoring-network:
    driver: bridge

volumes:
  mongo-data-dev:
  redis-data-dev:
